---
- name: this playbook is to pull image from dockerhub
  hosts: webserver
  become: true
  become_user: root
  become_method: sudo
  
  tasks:      
     - name: pull image from ecr
       shell:
         cmd: docker pull 400786363496.dkr.ecr.ap-south-1.amazonaws.com/newrepo:latest
       
     - name: start a container
       shell:
         cmd: docker run -d --name cont1 -p 8096:8080 400786363496.dkr.ecr.ap-south-1.amazonaws.com/newrepo:latest
